name: '💡 Feature Request (Starter Kit)'
description: "Have any idea for a new feature or enhancements to an existing one? Open an issue."
body:
- type: textarea
  attributes:
    label: Description
    placeholder: "What would you like to see added/improved?"
  validations:
    required: true
