title: 'Product with Variants'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: description
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          display: Description
          type: markdown
          icon: markdown
          listable: hidden
      -
        handle: product_variants
        field:
          display: 'Product Variants'
          type: product_variants
          icon: product_variants
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: product_categories
        field:
          type: terms
          taxonomies:
            - product_categories
          display: 'Product Categories'
          mode: select
