title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
      -
        handle: description
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          type: markdown
          localizable: false
          listable: hidden
          display: Description
      -
        handle: listing_image
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          max_files: 1
          type: assets
          instructions: 'Will be displayed on product listing pages.'
          localizable: false
          listable: hidden
          display: 'Listing Image'
  sidebar:
    display: Sidebar
    fields:
      -
        handle: price
        field:
          read_only: false
          type: money
          localizable: false
          listable: hidden
          display: Price
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
      -
        handle: product_categories
        field:
          type: terms
          taxonomies:
            - product_categories
          display: 'Product Categories'
          mode: select
